version: "3.7"

services:
  app:
    build:
      context: .
    env_file:
      - rails.env
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules

    environment:
      DB_HOST: db
      RAILS_MAX_THREADS: 5
      PORT: 3000

    ports:
      - 3000:3000
    restart: always
    depends_on:
      - "db"

  db:
    image: postgres:13-alpine
    env_file:
      - db.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: your_db_password
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6.0.8-alpine

volumes:
  pgdata:
  gem_cache:
  node_modules: